# Site settings
title: WooChain | internets first smart data system through the globalization of peer2peer networks
description: WooChain | internets first smart data system through the globalization of peer2peer networks
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: WooChain
user_description: WooChain | internets first smart data system through the globalization of peer2peer networks
user_title: Put your data where your mouth is


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
